#!/usr/bin/env ruby
# ct - count files and directories
# Copyright (C) 2013 Hans-Nikolai Viessmann
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
require './trollop'

VERSION = 0.5-1

def all_count
	list = Dir.glob("{*,.*}") - [".",".."]
	puts "IN - #{Dir.pwd}", "---> #{list}" if $opts[:verbose]
	count = list.length
	return all_rec_count(count) if $opts[:recursive] and count > 0
	count
end

def dir_count
	list = Dir.glob("{*,.*}") - [".",".."]
	puts "IN - #{Dir.pwd}", "---> #{list}" if $opts[:verbose]
	count = list.count{|obj| File.directory?(obj) and not File.symlink?(obj)}
	return dir_rec_count(count) if $opts[:recursive] and count > 0
	count
end

def fil_count
	list = Dir.glob("{*,.*}") - [".",".."]
	puts "IN - #{Dir.pwd}", "---> #{list}" if $opts[:verbose]
	list.count{|obj| File.file?(obj)}
end

def sym_count
	list = Dir.glob("{*,.*}") - [".",".."]
	puts "IN - #{Dir.pwd}", "---> #{list}" if $opts[:verbose]
	list.count{|obj| File.symlink?(obj)}
end

def dir_rec_count(count)
	list = Dir.glob("{*,.*}") - [".",".."]
	puts "IN - #{Dir.pwd}", "---> #{list}" if $opts[:verbose]
	list.select{|obj| File.directory?(obj) and not File.symlink?(obj)}.each do |dir|
		Dir.chdir(dir) do
			count += dir_count
		end
	end
	count
end

def all_rec_count(count)
	list = Dir.glob("{*,.*}") - [".",".."]
	puts "IN - #{Dir.pwd}", "---> #{list}" if $opts[:verbose]
	list.each do |objs|
		if File.directory?(objs) and not File.symlink?(objs)
			Dir.chdir(objs) do
				count += all_count
			end
		end
	end
	count
end

def count(path)
	Dir.chdir(path) do
		if $opts.values_at(:files, :dirs, :syms).all? or $opts.values_at(:files, :dirs, :syms).all?{|opt| !opt}
			all_count
		elsif $opts[:files]
			fil_count
		elsif $opts[:dirs]
			dir_count
		elsif $opts[:syms]
			sym_count
		else
			puts "No Match"
			exit 95
		end
	end
end

$opts = Trollop::options do
	version "ct #{VERSION} (c) 2013 Hans-Nikolai Viessmann"
	text <<-EOF
ct Copyright (c) 2013 Hans-Nikolai Viessmann
This program comes with ABSOLUTELY NO WARRANTY!

Usage: ct [OPTIONS] ... DIR

DESCRIPTION: Count the number of files and directories within DIR

OPTIONS:
EOF
	opt :files, "Return only file count" 
	opt :dirs, "Return only directory count"
	opt :syms, "Return only symbolic link count"
	opt :recursive, "Recursively count"
	opt :verbose, "Show more detail"
end

if ARGV.length != 1
	puts "No arguments given. Try '--help' for options."
	exit 125
end

path = ARGV.shift

if not File.directory?(path)
	puts "Invalid path given -- #{path}"
	exit 100
end

path = File.realdirpath(path)

puts "GO - #{path}" if $opts[:verbose]

puts count(path)
