#!/usr/bin/env ruby
require 'getoptlong'

VERSION = 0.4

def all_count
	count = (Dir.glob("{*,.*}") - [".",".."]).length
	return all_rec_count(count) if $rec and count > 0
	count
end

def dir_count
	count = (Dir.glob("{*,.*}") - [".",".."]).count{|obj| File.directory?(obj) and not File.symlink?(obj)}
	return dir_rec_count(count) if $rec and count > 0
	count
end

def fil_count
	(Dir.glob("{*,.*}") - [".",".."]).count{|obj| File.file?(obj)}
end

def dir_rec_count(count)
	(Dir.glob("{*,.*}") - [".",".."]).select{|obj| File.directory?(obj) and not File.symlink?(obj)}.each do |dir|
		Dir.chdir(dir) do
			count += dir_count
		end
	end
	count
end

def all_rec_count(count)
	(Dir.glob("{*,.*}") - [".",".."]).each do |objs|
		if File.directory?(objs) and not File.symlink?(objs)
			Dir.chdir(objs) do
				count += all_count
			end
		end
	end
	count
end

def count(path, type)
	Dir.chdir(path) do
		case type
			when 0
				all_count
			when 1
				fil_count
			when 2
				dir_count
		end
	end
end

opts = GetoptLong.new(
	['--help', '-h', GetoptLong::NO_ARGUMENT],
	['--recursive', '-r', GetoptLong::NO_ARGUMENT],
	['--verbose', '-v', GetoptLong::NO_ARGUMENT],
	['--files', GetoptLong::NO_ARGUMENT],
	['--dirs', GetoptLong::NO_ARGUMENT],
	['--version', '-V', GetoptLong::NO_ARGUMENT]
)

$rec = false
$ver = false
cho = 0

opts.each do |opt, arg|
	case opt
	when '--help'
		puts <<-EOF
Usage: ct [OPTION] ... DIR

OPTIONS:
  -h, --help		show this message
  -v, --verbose		verbose
  -r, --recursive	recursively count directories
  --files		return only file count
  --dirs		return only directory count
  -V, --version		print version
		EOF
		exit 0
	when '--recursive'
		$rec = true
	when '--verbose'
		$ver = true
	when '--files'
		cho = 1
	when '--dirs'
		cho = 2
	when '--version'
		puts "ct #{VERSION}"
		exit 0
	end
end

if ARGV.length != 1
	puts "No arguments given. Try '--help' for options."
	exit 125
end

path = ARGV.shift

if not File.directory?(path)
	puts "Invalid path given -- #{path}"
	exit 100
end

puts count(File.realdirpath(path), cho)
